FROM node:latest as build-stage
WORKDIR /client-app
COPY ./client/package*.json .
COPY ./.env .
RUN npm install
COPY ./client/ .
RUN npm run client:build

FROM nginx as production-stage
RUN mkdir /client-app
COPY --from=build-stage /client-app/dist /client-app
COPY ./client/nginx.conf /etc/nginx/nginx.conf