version: "3"
services:
  database:
    image: mongo:6.0.2
    volumes:
      - ${VOLUME_PATH_DB}:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      - MONGO_INITDB_DATABASE=boardgamegallerie
    restart: always
    deploy:
      restart_policy:
        delay: 3s
        max_attempts: 5
    expose:
      - 27017

  api:
    build:
      context: ./
      dockerfile: ./Dockerfile.api
    restart: always
    deploy:
      restart_policy:
        delay: 3s
        max_attempts: 5
    depends_on:
      - database
    ports:
      - "${API_PORT}:3000"

  frontend-client:
    build:
      context: ./
      dockerfile: ./Dockerfile.client
    depends_on:
      - api
    ports:
      - "${CLIENT_PORT}:80"

  frontend-admin:
    build:
      context: ./
      dockerfile: ./Dockerfile.admin
    depends_on:
      - api
    ports:
      - "${ADMIN_PORT}:80"