-- AlterTable
ALTER TABLE "Answers" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Game" ALTER COLUMN "imgUrl" DROP NOT NULL,
ALTER COLUMN "videoUrl" DROP NOT NULL,
ALTER COLUMN "deleted" SET DEFAULT false,
ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "GameQuestion" ALTER COLUMN "deleted" SET DEFAULT false,
ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "tutorial" SET DEFAULT true,
ALTER COLUMN "role" SET DEFAULT 'user',
ALTER COLUMN "deleted" SET DEFAULT false,
ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP;
